version: '2'
services:
  jenkins:
    build: .
    container_name: jenkins
    user: jenkins
    volumes:
      - /opt/jenkins/data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "/opt/jenkins/data/jenkins"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
